spring:
  profiles:
    active: test
---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
      url: r2dbc:mysql://localhost:3306/medibuddy
      username: root
      password: Root@1234

