spring:
  profiles:
    active: local

---

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/balaramkrishna1771/learning-curve.git
          clone-on-start: true
          default-label: dev
          search-paths: Reactive Programming using Spring WebFlux/student-app/students-app-config-repo
---
encrypt:
  key: MySecretSymmetricKey123!
---

server:
  port: 8888
