spring:
  application:
    name: students-info-service
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
      name: students-info-service, shared-config
