spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/school_db
    username: root
    password: "{cipher}5fb472e807e8b1b91ffb45c31b3ba33c55578d5b51fc5eeb6a2853a7e652d032"

---

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
rabbitmq:
  queue:
    studentsInfoQueue: students-info-queue
    paymentsQueue: payments-queue
    infoResponseQueue: info-response-queue
    payemtsResponseQueue: payments-response-queue
  exchange:
    studentServiceExchange: students-service-exchange
  routingKeys:
    studentsInfoRoutingKey: student.info.request
    paymentsRoutingKey: payment.request
    infoResponseRoutingKey: studentInfo.response
    paymentResponseRoutingKey: payment.response

---
spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

---
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  kafka:
    template:
      default-topic: student-info-topic
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    topic: "student-info-events"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
    consumer:
      group-id: webflux-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    admin:
      properties:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
