spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/school_db
    username: root
    password: "{cipher}5fb472e807e8b1b91ffb45c31b3ba33c55578d5b51fc5eeb6a2853a7e652d032"

---

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
rabbitmq:
  queue:
    studentsInfoQueue: students-info-queue
    paymentsQueue: payments-queue
    responseQueue: response-queue
  exchange:
    studentServiceExchange: students-service-exchange
  routingKeys:
    studentsInfoRoutingKey: student.info.request
    paymentsRoutingKey: payment.request
    responseRoutingKey: student.response